# Generated by Django 3.1.4 on 2020-12-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=10000)),
                ('username', models.CharField(max_length=10000)),
            ],
            options={
                'unique_together': {('url', 'username')},
            },
        ),
    ]
